### ISSUE TITLE
librwctl

### ISSUE THREAD

**Issue by evrynet1** [CpanelInc/tech-CSI#12]
Hi @cPanelPeter 

I hope you doing fine. One of our servers has been flagged with:

Suspicious file found: /lib64/librwctl.so
    \_ Size: 39552 Date Changed: Sat May 11 10:11:11 2022 PKG Is Owned: No Owned by U/G: root/root

and I was wondering if you could provide me some more info about this? I couldn't find any malwares or hacks or vulnernabilities related to this file (at least in Google). The original file is dated back to 2014 although I couldn't find the same file on some of our other servers so I'm a bit lost here. Do you know why was this specific .so file added as suspicious? Do you know to which vulnerability/malware could this be related to?

Thanks as always

**Comment by cPanelPeter** [comment]
Hello, 

Unless you installed this from source, this doesn't look good.  I would grab the sha256sum from that file and check it at Virustotal.com.  

If you want one of our analysts to investigate it further, please open a support ticket.  We can check and see if this is a new rootkit or not.  Just submit your ticket and say attention L3 or Peter.  

Thanks.
