### ISSUE TITLE
new detection perfctl

### ISSUE THREAD

**Issue by JQuags** [CpanelInc/tech-CSI#20]
This was a root compromise

Running in cron /root/.config/cron/perfcc

75e5f4c549cfbb999b0ece7c842321f2ccca6cd62d2274f27132b734a146108e  /root/.config/cron/perfcc

process was called perfcc 

exe -> '/tmp/.perf.c/perfctl (deleted)'

**Comment by cPanelPeter** [comment]
Update detections for Linux/Agent.OE trojan reported by Quags

Thank you.
