### ISSUE TITLE
malware in /bin/passwd 

### ISSUE THREAD

**Issue by mailbaby** [CpanelInc/tech-CSI#21]
/usr/bin/passwd
sha256
e84636cf7f19dcded99c7fd173a6b4132dfe33ef761e27d457aa0bccb154240a 

md5
9834635f38e58adf2131c1037403e101

I believe this can be detected in the sha256 file

On reset we see a call to a remote ip via /usr/bin/passwd

```

write(1, "\n", 1
)                       = 1
ioctl(0, TCGETS, {B9600 opost isig icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B9600 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B9600 opost isig icanon echo ...}) = 0
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=100000000}, 0x7ffe6d90f750) = 0
write(1, "passwd: all authentication token"..., 56passwd: all authentication tokens updated successfully.
) = 56
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(1010), sin_addr=inet_addr("179.43.142.41")}, 16) = 0
sendto(3, "GET /pass?pass=cm9vdCAsICAsIHRlc"..., 181, MSG_NOSIGNAL, NULL, 0) = 181
recvfrom(3, "HTTP/1.1 200 OK\r\nServer: Werkzeu"..., 4000, 0, NULL, NULL) = 176
close(3)   
```

**Comment by cPanelPeter** [comment]
Hello, 

Thank you for the information. The sha256sum hash changes with each operating system, so we cannot just add that hash based on this. Additionally, VirusTotal.com shows nothing found for that hash, so it's not considered malicious.

https://www.virustotal.com/gui/file/e84636cf7f19dcded99c7fd173a6b4132dfe33ef761e27d457aa0bccb154240a

I would need a bit more information on what you found to indicate the problem. I do see in your strace what looks to be a password in plain text, but without more context as to what this is from, I don't have enough to go on.
