### ISSUE TITLE
 getcontrolpaneluserspackages incorrectly flagged on CloudLinux systems

### ISSUE THREAD

**Issue by rbairwell** [CpanelInc/tech-CSI#22]
It appears - via https://support.cpanel.net/hc/en-us/community/posts/21424281340567-should-be-dhcpd-cryptominer-or-dhpcd-cryptominer - that tech-CSI detects the presence of
`/usr/bin/getcontrolpaneluserspackage`
as "dhcpd cryptominer" as https://github.com/CpanelInc/tech-CSI/blob/7065d50c4755ac82cbf1ddb3957e245442f2dcf4/csi.pl#L2731-L2732 just looks for file names in /bin/  consisting of at least 26 characters ("getcontrolpaneluserspackage" being 29 in length).

A check should be made to see if "CloudLinux" is the OS and, if so, add an exclude for that specific string in that test - or the check tightened to `=~ m/\A[a-z0-9]{26}\z/` to ensure that strings with EXACTLY 26 characters are matched.

(Also, as per that forum post and [Akamai's write up](https://www.akamai.com/blog/security-research/dhpcd-cryptominer-hid-four-years), the malware should be called "dhpcd cryptominer" (not dh**cp**d).

**Comment by cPanelPeter** [comment]
Hey Richard, 

Thank you for this. I actually ran into this Friday evening and have a case open to check for CL9 and that file to ignore it, but I like your solution better and will likely implement this in the next version.
