### ISSUE TITLE
Missing closing parenthesis in csi.pl

### ISSUE THREAD

**Issue by MsJamie** [CpanelInc/tech-CSI#23]
Hi,

In the latest update there is an error in csi.pl

The commit here https://github.com/CpanelInc/tech-CSI/commit/14a802c46ee023ad2213a333ba76c04ad84f7a66

Is causing this error message
```
[root@cpanel ~]# /usr/local/cpanel/3rdparty/bin/perl csi.pl 
syntax error at csi.pl line 2481, near ");"
BEGIN not safe after errors--compilation aborted at csi.pl line 2564.
```

For line 2481
```
    push( @SUMMARY, expand( "\t\\_ $find_sedexp" );
```

That should be as follows, it's just missing the last closing parenthesis

```
    push( @SUMMARY, expand( "\t\\_ $find_sedexp" ));
```

**Comment by cPanelPeter** [comment]
Thank you, 

This is now fixed and publicly available.
