### ISSUE TITLE
Very slow find with check_auth_keys_for_commands script

### ISSUE THREAD

**Issue by xBouncyBear** [CpanelInc/tech-CSI#24]
Hello!

We have problem with the following check: check_auth_keys_for_commands
This check search authorized_keys in "/". This check in our server is very slow and that find end time is maybe 8-10 days / server.
Is it possible to exclude this find script somehow, or exclude some path where dont search authorized_keys file?
We have /backup on all server and this mount point size 3-4 TB / server, maybe the problem is this script running to /backup too, but we have lots of files in /backup and maybe that why this script running few days.

If you need more information please let me know.

Thanks,
Mark

**Comment by cPanelPeter** [comment]
Hello Mark, 

Thanks for your report. Indeed, it will check everything under / (including /backup). 
For now, I will add a simple switch (--skiipauthchk) which you can add to the --full call and it will skip that one check.

Future plans are to add a config file of some kind that can be used to run/skip various checks based on that config.

**Comment by xBouncyBear** [comment]
Hello!

Thank you!

It works fine, but "--skipauthchk" function is not work only "--skip_authchk" little typo problem maybe.

**Comment by cPanelPeter** [comment]
Good catch. Thank you. This should be fixed and --skipauthchk should be the option now.  Please let me know if you see any other issues.
