### ISSUE TITLE
Possible False Positive hiddenwasp port detection

### ISSUE THREAD

**Issue by raisulmushfeq** [CpanelInc/tech-CSI#25]
On lsof version 4.94.0 and CloudLinux release 9.3
It seems to be showing the following error (When **Run from WHM Terminal**, not from SSH Terminal):
```
> Found socket listening on port tcp:61091. Could indicate possible root compromise
> Found socket listening on port tcp:65130. Could indicate possible root compromise
> Found socket listening on port tcp:65439. Could indicate possible root compromise
> Found socket listening on port tcp:1234. Could indicate possible root compromise
> Found socket listening on port tcp:25905. Could indicate possible root compromise
> Found socket listening on port tcp:8816. Could indicate possible root compromise
```
On all of the servers with same software version. I have checked manually and no such ports are open. And the same port list is showing on all the servers with same version.
When I tried to debug the code with:
```
foreach my $port (@ports) {
    chomp($port);
    my $lsof = Cpanel::SafeRun::Timed::timedsaferun( 4, 'lsof', '-i', $port );
    # Added the following debugging line
    print "$lsof\n";
    # If lsof returns results, log the findings
    if ($lsof) {
        push @SUMMARY, "> Found socket listening on port $port. Could indicate possible root compromise";
    }
}
```

it seems to be printing the error "Timeout while executing: lsof -i tcp:61091"
Could it be possible this is giving a false positive warning on all the servers running this version of lsof/OS release?

Please let me know if you need any other information.

**Comment by cPanelPeter** [comment]
Hello, 

Thank you for your report. However, I am not able to duplicate this. The lsof command runs and if it takes longer than 4 seconds to return a value, then the value returned is a Timeout.  

Something on your servers is making the lsof command take longer than 4 seconds.

`# grep PRETTY_NAME /etc/os-release ; rpm -q lsof
PRETTY_NAME="CloudLinux 9.4 (Vladimir Vasyutin)"
lsof-4.94.0-3.el9.x86_64
`

`
# for port in 61091 65130 65439 1234 25905 8816 ; do lsof -i tcp:$port ; done
# 
`

I can try and trap the timeout but ultimately this is a system server issue.

**Comment by raisulmushfeq** [comment]
Hello,

Did you run this from WHM terminal? Because I do not face this issue when logged in to the server via SSH, only from WHM Terminal.
When I run your code
`for port in 61091 65130 65439 1234 25905 8816 ; do lsof -i tcp:$port ; done`
from whm terminal, it gets stuck, and does not complete (waits for the command to finish)
But when I run the same command from SSH, it completes within 1 second.

Hope that helps.

**Comment by cPanelPeter** [comment]
Hello, 

Thank you for the additional details. I have confirmed that running some commands such as lsof via the WHM Terminal do take much longer to complete. Checking with the developers, this is expected based on how the terminal system was written/implemented.  

Please also note, CSI is never intended to be run via the WHM Terminal.  This is unsupported.
