### ISSUE TITLE
Elasticsearch falsely identified as rpm/yum process

### ISSUE THREAD

**Issue by georgetasioulis** [CpanelInc/tech-CSI#5]
Hello,

Trying to run csi.pl when an elasticsearch instance is running on the server, gives the following error:
```
[WARN]: An rpm/yum process may be running. Could cause some checks to hang waiting for process to complete.
```
One of the command line arguments of elasticsearch is `-Des.distribution.type=rpm` so apparently that's causing the false negative.

**Comment by cPanelPeter** [comment]
Thank you for reporting this.  Next version (about to be released) will have a fix for this.
