### ISSUE TITLE
Malicius sshins

### ISSUE THREAD

**Issue by devisbal** [CpanelInc/tech-CSI#6]
I just recently found this on one system:
https://www.joesandbox.com/analysis/355141/0/html
Can you add this check on /etc/ld.so.preload look for  /lib64/libs.so
More info on page.

**Comment by cPanelPeter** [comment]
Hello, 

Thank you for the information. I'll make plans to add detections for this in the next release. 
Can you tell me specifically which files you found on your server?  Was the /lib64/libs.so found only in the /etc/ld.so.preload or was it physically on the server as well?

**Comment by devisbal** [comment]
Hello: 


There was the entry on: /etc/ld.so.preload with /lib64/libs.so that was a symbolic link to the /usr/lib64/libs.so that was the malicious code, and all the process on the server did has this .so loaded. 


----- Original Message -----

**Comment by cPanelPeter** [comment]
Note: this file path was added to the suspicious_files.txt file.  It should. now detect this.   Thank you. again for. reporting. it.
