### ISSUE TITLE
/tmp/dr_client source or sample?

### ISSUE THREAD

**Issue by adulau** [CpanelInc/tech-CSI#7]
Thanks a lot for your nifty list of potential suspicious files. I recently saw that you added /tmp/dr_client? Do you remember the source or even the hash of the file?

https://github.com/CpanelInc/tech-CSI/blame/81dc4919366e80421a0cfa6166938cf5cc8cd34b/suspicious_files.txt#L444

**Comment by cPanelPeter** [comment]
Hello, 

Sorry, sadly I do not remember the source. It was either likely found in a ticket we found and related to a coin miner or it was obtained from a list of suspicious files from virustotal.com or another malware analysis site.  

Do you believe it is a false-positive?  If so, I can remove it.  But so far I have not seen it on any clean CentOS/CloudLinux operating systems.

**Comment by adulau** [comment]
Thanks it was not a FP at all. And I have the strong impression, it's kind of targeted malware. If you remember where you got it, let me know. Thank you very much.
