### ISSUE TITLE
id: extra operand ‘2>/dev/null’

### ISSUE THREAD

**Issue by evrynet1** [CpanelInc/tech-CSI#9]
On multiple servers when we run csi.pl we are getting the following now:

[ Checking /etc/passwd file for suspicious users ]
id: extra operand ‘2>/dev/null’
Try 'id --help' for more information.
id: extra operand ‘2>/dev/null’
Try 'id --help' for more information.

we run it with the following command:

/usr/local/cpanel/3rdparty/bin/perl <(curl -L -s "https://raw.githubusercontent.com/CpanelInc/tech-CSI/master/csi.pl")

**Comment by cPanelPeter** [comment]
Thank you for reporting this.  I'll get it addressed as soon as possible.

**Comment by cPanelPeter** [comment]
V3.5.1 should address this issue.

**Comment by evrynet1** [comment]
@cPanelPeter I'm reopening this as I just had a client with CentOS 7 and the script exist at "Checking process list for suspicious processes" so it looks like the fix you applied is not okay with CentOS 7. Can you have a look?

Thanks
